"""initial_schema

Revision ID: 01405d0d5989
Revises: 
Create Date: 2026-02-27 11:51:54.808658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01405d0d5989'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_schedules_id'), table_name='route_schedules')
    op.drop_index(op.f('uq_route_departure_time'), table_name='route_schedules')
    op.drop_table('route_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_schedules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('departure_time', mysql.TIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('route_schedules_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_route_departure_time'), 'route_schedules', ['route_id', 'departure_time'], unique=True)
    op.create_index(op.f('ix_route_schedules_id'), 'route_schedules', ['id'], unique=False)
    # ### end Alembic commands ###
