"""Add payment_status and payment_method to packages

Revision ID: 3b6923faf586
Revises: 07da8aaee1d1
Create Date: 2026-02-27 20:33:30.846919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b6923faf586'
down_revision: Union[str, Sequence[str], None] = '07da8aaee1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('payment_status', sa.String(length=50), nullable=False, server_default='paid_on_send'))
    op.add_column('packages', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'payment_method')
    op.drop_column('packages', 'payment_status')
    # ### end Alembic commands ###
