"""Add owner models

Revision ID: eba9585ef1d2
Revises: ffd1cca5a56a
Create Date: 2026-03-15 22:55:12.858128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba9585ef1d2'
down_revision: Union[str, Sequence[str], None] = 'ffd1cca5a56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add 'OWNER' to the UserRole enum in the users table
    op.execute("ALTER TABLE users MODIFY COLUMN `role` ENUM('ADMIN','SECRETARY','DRIVER','ASSISTANT','CLIENT','USER','OWNER') NOT NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('cash_transaction_id', sa.Integer(), nullable=False),
    sa.Column('secretary_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_transaction_id'], ['cash_transactions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['secretary_id'], ['secretaries.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_withdrawals_id'), 'owner_withdrawals', ['id'], unique=False)
    # NOTE: route_schedules drop removed - it was an unintended auto-generated side effect
    with op.batch_alter_table('buses') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_buses_owner_id', 'persons', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove 'OWNER' from the UserRole enum in the users table
    op.execute("ALTER TABLE users MODIFY COLUMN `role` ENUM('ADMIN','SECRETARY','DRIVER','ASSISTANT','CLIENT','USER') NOT NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses') as batch_op:
        batch_op.drop_constraint('fk_buses_owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')
    # NOTE: route_schedules recreation removed - table was never dropped
    op.drop_index(op.f('ix_owner_withdrawals_id'), table_name='owner_withdrawals')
    op.drop_table('owner_withdrawals')
    op.drop_table('owners')
    # ### end Alembic commands ###
