%% Diagrama de Objetos: Ejemplo de instancias en un escenario concreto
classDiagram
    object client1 : Client
    object trip1 : Trip
    object bus1 : DoubleDeckBus
    object ticket1 : Ticket
    object reservation1 : Reservation

    client1 --> ticket1 : compra
    client1 --> reservation1 : reserva
    ticket1 --> trip1 : pertenece a
    trip1 --> bus1 : asignado a
